### ISSUE TITLE
error while runnin playbook

### ISSUE THREAD

**Issue by Aur0nd** [robertdebock/ansible-role-openvpn#5]
Greetings mate,

I just ran your roles but I'm encountering an error
`{"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'content'\n\nThe error appears to be in '/Users/gz/Documents/PublicKeys/roles/robertdebock.openvpn/tasks/main.yml': line 33, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: distribute static encryption key\n  ^ here\n"}`

I did install "ansible-galaxy install -r requirements.txt".

Many thanks,
George

**Comment by robertdebock** [comment]
Hi,

Sorry, the role is a mess at the moment, it indeed does not work as expected.

I'll try to fix things later and release a new version. Keeping this issue open until the role is in a better state.

Regards, Robert.

**Comment by Aur0nd** [comment]
Thanks so much buddy for letting me know, I thought I was being an idiot as always

**Comment by robertdebock** [comment]
The role is in a better shape now. If you'd like to, please try it and let me know if it works for you.

**Comment by Aur0nd** [comment]
Greetings mate,

I just retried everything from scratch, I downloaded the requirements and created the playbook you've written in your README file but I get the error below:

`TASK [robertdebock.openvpn : install openvpn packages] *************************************************************************************************************************************************************
fatal: [open]: FAILED! => {"changed": false, "msg": "No package matching 'openvpn' found available, installed or updated", "rc": 126, "results": ["No package matching 'openvpn' found available, installed or updated"]}

`

**Comment by Aur0nd** [comment]
This is what I get on ubuntu:

`TASK [robertdebock.openvpn : install openvpn packages] *************************************************************************************************************************************************************
fatal: [open]: FAILED! => {"changed": false, "msg": "No package matching 'easy-rsa' is available"}
`

**Comment by Aur0nd** [comment]
One more thing buddy..

When I cd molecule/defaults and run molecule test

I get this error: CRITICAL 'molecule/default/molecule.yml' glob failed.  Exiting.

It seems that it can't even see the config for some reason - I'm not sure if I'm doing something wrong as I'm completely new to the galaxy roles :)

**Comment by robertdebock** [comment]
About the molecule test, you can run it from the root of the role, something like this:

```shell
cd robertdebock.openvpn
molecule test
```

What distribution are you trying to setup VPN on? It's been tested on: (copy-paste from `meta/main.yml`)

```yaml
    - name: Amazon
      versions:
        - Candidate
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
```
