### ISSUE TITLE
missing /etc/openvpn/easy-rsa/pki dir

### ISSUE THREAD

**Issue by gadelkareem** [robertdebock/ansible-role-openvpn#9]
## Describe the bug
missing /etc/openvpn/easy-rsa/pki dir

## Playbook
```
- src: robertdebock.openvpn
- src: robertdebock.bootstrap
```

```yaml
- name: Deploy 
  hosts: all
  gather_facts: True
  become: yes
  roles:
  - { role: robertdebock.bootstrap, tags: [ 'openvpn' ] }
  - { role: robertdebock.openvpn, tags: [ 'openvpn' ] }
```

## Output
```
TASK [robertdebock.openvpn : openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key] *******************************************************************************************************************************************
fatal: []: FAILED! => {"changed": true, "cmd": ["openvpn", "--genkey", "--secret", "/etc/openvpn/easy-rsa/pki/ta.key"], "delta": "0:00:00.020160", "end": "2021-05-17 16:15:18.475006", "msg": "non-zero return code", "rc": 1, "start": "2021-05-17 16:15:18.454846", "stderr": "", "stderr_lines": [], "stdout": "Mon May 17 16:15:18 2021 Cannot open shared secret file '/etc/openvpn/easy-rsa/pki/ta.key' for write: No such file or directory (errno=2)\nMon May 17 16:15:18 2021 Exiting due to fatal error", "stdout_lines": ["Mon May 17 16:15:18 2021 Cannot open shared secret file '/etc/openvpn/easy-rsa/pki/ta.key' for write: No such file or directory (errno=2)", "Mon May 17 16:15:18 2021 Exiting due to fatal error"]}

```
## Environment
```
> cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

> ansible --version
ansible 2.9.21

> cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```

## fix
```
mkdir -p /etc/openvpn/easy-rsa/pki
```
